import {createAsyncThunk, createSlice} from '@reduxjs/toolkit';

// service
import {MovieService} from '../../service/movie/movieService';

// types
import {MovieDetail, MovieType} from '../../service/movie/interface';
import {RootState} from '..';
import {discoverMovieKeys, discoverMoviePrefix} from './discoverMovieKeys';

export interface DiscoverMovieState {
  movieList: MovieType[];
  movieDetail: MovieDetail | null;
  status: 'idle' | 'loading' | 'failed';
}

const initialState: DiscoverMovieState = {
  movieList: [],
  movieDetail: null,
  status: 'idle',
};

export const getMovieListAsync = createAsyncThunk(
  discoverMovieKeys.fetchList,
  async () => {
    try {
      const response = await MovieService.getMovieList();
      return response.data || {};
    } catch (err: any) {
      console.log(err.message);
    }
  },
);

export const getMovieByIdAsync = createAsyncThunk(
  discoverMovieKeys.fetchById,
  async (movieId: number) => {
    const response = await MovieService.getMovieDetail(movieId);
    return response.data || {};
  },
);

export const discoverMovieSlice = createSlice({
  name: discoverMoviePrefix,
  initialState,
  // The `reducers` field lets us define reducers and generate associated actions
  reducers: {},
  // The `extraReducers` field lets the slice handle actions defined elsewhere,
  // including actions generated by createAsyncThunk or in other slices.
  extraReducers: builder => {
    builder
      .addCase(getMovieListAsync.pending, state => {
        state.status = 'loading';
      })
      .addCase(getMovieListAsync.fulfilled, (state, action) => {
        state.status = 'idle';
        state.movieList = action.payload?.results || [];
      })
      .addCase(getMovieListAsync.rejected, state => {
        state.status = 'failed';
      })
      .addCase(getMovieByIdAsync.pending, state => {
        state.status = 'loading';
      })
      .addCase(getMovieByIdAsync.fulfilled, (state, action) => {
        state.status = 'idle';
        state.movieDetail = action.payload;
      })
      .addCase(getMovieByIdAsync.rejected, state => {
        state.status = 'failed';
      });
  },
});

export const selectMovieList = (state: RootState) =>
  state.discoverMovie.movieList;
export const selectMovieDetail = (state: RootState) =>
  state.discoverMovie.movieDetail;
export const selectMovieState = (state: RootState) =>
  state.discoverMovie.status;

export default discoverMovieSlice.reducer;
